/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouwei_jnisample_java_jni_JNISample */

#ifndef _Included_com_zhouwei_jnisample_java_jni_JNISample
#define _Included_com_zhouwei_jnisample_java_jni_JNISample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhouwei_jnisample_java_jni_JNISample
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample_java_1jni_JNISample_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
